[workspace]
members = [
    "src/axis",
    "src/mlp",
    "src/cnn",
    "src/attention",
    "src/addition",
    "src/mnist",
    "src/mnist-population",
    "src/panel",
]
default-members = ["src/mlp"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
publish = false

[workspace.dependencies]
cutile = "=0.3.1"
axis = { path = "src/axis" }
