#!/usr/bin/env bash
set -euo pipefail

workspace_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
scan_root="$(cd -- "$workspace_root/../research" && pwd)"
output="$workspace_root/data/evidence/default-census.md"

while (( $# )); do
    case "$1" in
        --root)
            scan_root="$(cd -- "${2:?--root requires a directory}" && pwd)"
            shift 2
            ;;
        --output)
            output="${2:?--output requires a path}"
            shift 2
            ;;
        *)
            printf 'unknown argument: %s\n' "$1" >&2
            exit 2
            ;;
    esac
done

temporary="$(mktemp -d)"
trap 'rm -r -- "$temporary"' EXIT
files_list="$temporary/files"
events="$temporary/events"
: >"$files_list"
: >"$events"

while IFS= read -r -d '' path; do
    relative="${path#"$scan_root"/}"
    skip=false
    IFS=/ read -r -a parts <<<"$relative"
    for part in "${parts[@]}"; do
        case "$part" in
            .*|archive|archived|build|data|node_modules|target|third_party|vendor|worktrees)
                skip=true
                break
                ;;
        esac
    done
    "$skip" || printf '%s\0' "$path" >>"$files_list"
done < <(find "$scan_root" -type f -name '*.py' -print0 | sort -z)

read -r files lines training_files < <(
    perl - "$events" "$files_list" <<'PERL'
use strict;
use warnings;

my ($events_path, $files_path) = @ARGV;
open my $events, '>', $events_path or die "cannot write $events_path: $!\n";
open my $paths, '<', $files_path or die "cannot read $files_path: $!\n";
local $/ = "\0";
my ($files, $lines, $training_files) = (0, 0, 0);
while (my $path = <$paths>) {
    $path =~ s/\0$//;
    next unless length $path;
    open my $source, '<', $path or die "cannot read $path: $!\n";
    $files++;
    my $has_training_call = 0;
    {
        local $/ = "\n";
        while (my $line = <$source>) {
            $lines++;
            $line =~ s/#.*$//;
            if ($line =~ /^\s*(batch|batch_size|bs|learning_rate|lr|epoch|epochs|n_epochs|num_epochs|random_seed|seed)(?:\s*:[^=]+)?\s*=\s*([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)/i) {
                my ($name, $value) = (lc $1, $2);
                my $category = $name =~ /^(?:batch|batch_size|bs)$/ ? 'batch_size'
                    : $name =~ /^(?:learning_rate|lr)$/ ? 'learning_rate'
                    : $name =~ /^(?:epoch|epochs|n_epochs|num_epochs)$/ ? 'epochs'
                    : 'seed';
                print {$events} "$category\t$value\n";
            }
            next if $line =~ /^\s*(?:class|def)\b/;
            while ($line =~ /\b(adamw|adam|sgd|rmsprop|adagrad|lion|binary_cross_entropy_with_logits|binary_cross_entropy|cross_entropy|smooth_l1_loss|l1_loss|mse_loss|nll_loss)\s*\(/ig) {
                my $name = lc $1;
                my $category = $name =~ /^(?:adamw|adam|sgd|rmsprop|adagrad|lion)$/ ? 'optimizer' : 'loss';
                print {$events} "$category\t$name\n";
                $has_training_call = 1;
            }
        }
    }
    $training_files++ if $has_training_call;
}
print "$files $lines $training_files\n";
PERL
)

format_counts() {
    local category="$1" rendered
    rendered="$({ awk -F '\t' -v category="$category" '$1 == category { print $2 }' "$events" \
        | LC_ALL=C sort \
        | uniq -c \
        | LC_ALL=C sort -k1,1nr -k2,2 \
        | head -12 \
        | awk 'BEGIN { separator = "" } { count = $1; $1 = ""; sub(/^ /, ""); printf "%s`%s` (%d)", separator, $0, count; separator = ", " }'; } || true)"
    printf '%s' "${rendered:-—}"
}

mkdir -p -- "$(dirname -- "$output")"
cat >"$output" <<EOF
# Python research default census

Generated by \`scripts/default_census.sh\` from \`$scan_root\`.

This is descriptive evidence, not a default policy. It scans active \`.py\`
files with a deliberately narrow lexical census and excludes hidden folders
plus archived, generated, data, dependency-vendor, worktree, target, and
virtual-environment folders. Literal single-line assignments and recognizable
call spellings are counted. Comments after \`#\` are discarded; strings and
multiline syntax are not parsed, so this lexical evidence can contain false
positives or omissions. Dynamically computed or config-file values, aliases,
custom optimizers, and semantic context are not inferred.

## Scope

| Measure | Count |
|---|---:|
| Python files considered | $files |
| Lines considered | $lines |
| Files with recognized optimizer/loss calls | $training_files |

## Recognized calls

| Choice | Observations |
|---|---|
| Optimizers | $(format_counts optimizer) |
| Loss functions | $(format_counts loss) |

## Literal configuration assignments

| Coordinate | Most frequent values |
|---|---|
| Batch size | $(format_counts batch_size) |
| Learning rate | $(format_counts learning_rate) |
| Epochs | $(format_counts epochs) |
| Seed | $(format_counts seed) |

Promote a default only after migrations establish that repeated spellings have
the same meaning. For example, a common batch size is still an optimization
choice; a class-loss reduction axis changes the mathematical objective and
must remain explicit.
EOF

printf 'wrote %s\n' "$output"
