#!/usr/bin/env python3
"""Measure repeated training choices in active Python research code.

This is descriptive evidence for API defaults, not an automatic policy maker.
It extracts literal assignments and recognizable optimizer/loss calls with the
standard library AST so results are deterministic and reviewable.
"""

from __future__ import annotations

import argparse
import ast
import collections
import pathlib

SKIP_PARTS = {
    ".git",
    ".venv",
    "__pycache__",
    "archive",
    "archived",
    "build",
    "data",
    "node_modules",
    "target",
    "third_party",
    "vendor",
    "worktrees",
}
NAMES = {
    "batch_size": {"batch", "batch_size", "bs"},
    "learning_rate": {"learning_rate", "lr"},
    "epochs": {"epoch", "epochs", "n_epochs", "num_epochs"},
    "seed": {"random_seed", "seed"},
}
OPTIMIZERS = {"adam", "adamw", "sgd", "rmsprop", "adagrad", "lion"}
LOSSES = {
    "binary_cross_entropy",
    "binary_cross_entropy_with_logits",
    "cross_entropy",
    "l1_loss",
    "mse_loss",
    "nll_loss",
    "smooth_l1_loss",
}


def qualified_name(node: ast.AST) -> str | None:
    parts: list[str] = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
        return ".".join(reversed(parts))
    return None


def literal_number(node: ast.AST) -> int | float | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
        return node.value
    if (
        isinstance(node, ast.UnaryOp)
        and isinstance(node.op, (ast.USub, ast.UAdd))
        and isinstance(node.operand, ast.Constant)
        and isinstance(node.operand.value, (int, float))
    ):
        sign = -1 if isinstance(node.op, ast.USub) else 1
        return sign * node.operand.value
    return None


def assignment_names(node: ast.Assign | ast.AnnAssign) -> list[str]:
    targets = node.targets if isinstance(node, ast.Assign) else [node.target]
    return [target.id.lower() for target in targets if isinstance(target, ast.Name)]


def format_counts(counts: collections.Counter[object], limit: int = 12) -> str:
    if not counts:
        return "—"
    return ", ".join(
        f"`{value}` ({count})"
        for value, count in sorted(
            counts.items(), key=lambda item: (-item[1], str(item[0]))
        )[:limit]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    default_root = pathlib.Path(__file__).resolve().parents[2]
    default_output = pathlib.Path(__file__).resolve().parents[1] / "data/default-census.md"
    parser.add_argument("--root", type=pathlib.Path, default=default_root)
    parser.add_argument("--output", type=pathlib.Path, default=default_output)
    args = parser.parse_args()

    values = {name: collections.Counter() for name in NAMES}
    optimizers: collections.Counter[str] = collections.Counter()
    losses: collections.Counter[str] = collections.Counter()
    files = lines = parsed = parse_failures = training_files = 0

    for path in sorted(args.root.rglob("*.py")):
        relative = path.relative_to(args.root)
        if any(part in SKIP_PARTS or part.startswith(".") for part in relative.parts):
            continue
        files += 1
        source = path.read_text(errors="replace")
        lines += source.count("\n") + bool(source)
        try:
            tree = ast.parse(source, filename=str(relative))
        except SyntaxError:
            parse_failures += 1
            continue
        parsed += 1
        file_has_training_call = False
        for node in ast.walk(tree):
            if isinstance(node, (ast.Assign, ast.AnnAssign)):
                value_node = node.value
                if value_node is None:
                    continue
                value = literal_number(value_node)
                if value is not None:
                    for assigned in assignment_names(node):
                        for category, aliases in NAMES.items():
                            if assigned in aliases:
                                values[category][value] += 1
            if isinstance(node, ast.Call):
                name = qualified_name(node.func)
                if name is None:
                    continue
                final = name.rsplit(".", 1)[-1].lower()
                if final in OPTIMIZERS:
                    optimizers[final] += 1
                    file_has_training_call = True
                if final in LOSSES:
                    losses[final] += 1
                    file_has_training_call = True
        training_files += file_has_training_call

    output = f"""# Python research default census

Generated by `scripts/default_census.py` from `{args.root}`.

This is descriptive evidence, not a default policy. It scans active `.py` files
with Python's AST and excludes hidden folders plus archived, generated, data,
dependency-vendor, worktree, target, and virtual-environment folders. Literal assignments and
recognized call names are counted; dynamically computed/config-file values,
aliases, custom optimizers, and semantic context are not inferred.

## Scope

| Measure | Count |
|---|---:|
| Python files considered | {files} |
| Parsed files | {parsed} |
| Parse failures | {parse_failures} |
| Lines considered | {lines} |
| Files with recognized optimizer/loss calls | {training_files} |

## Recognized calls

| Choice | Observations |
|---|---|
| Optimizers | {format_counts(optimizers)} |
| Loss functions | {format_counts(losses)} |

## Literal configuration assignments

| Coordinate | Most frequent values |
|---|---|
| Batch size | {format_counts(values['batch_size'])} |
| Learning rate | {format_counts(values['learning_rate'])} |
| Epochs | {format_counts(values['epochs'])} |
| Seed | {format_counts(values['seed'])} |

Promote a default only after migrations establish that repeated spellings have
the same meaning. For example, a common batch size is still an optimization
choice; a class-loss reduction axis changes the mathematical objective and
must remain explicit.
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output)
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
